/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Datapoint from the Echo System": {              "en": "Datapoint from the Echo System",                  "de": "Datenpunkt aus dem Echo-System",                  "ru": "Datapoint из системы Echo",                       "pt": "Datapoint do Echo System",                        "nl": "Datapunt van het echosysteem",                    "fr": "Point de données du système Echo",                "it": "Datapoint da Echo System",                        "es": "Punto de datos del sistema Echo",                 "pl": "Punkt danych z systemu Echo",                     "zh-cn": "来自回声系统的数据点"},
    "Meal plan": {                                   "en": "Meal plan",                                       "de": "Essensplan",                                      "ru": "План Питания",                                    "pt": "Plano de refeição",                               "nl": "Maaltijdplan",                                    "fr": "Plan de repas",                                   "it": "Piano pasto",                                     "es": "Régimen de comidas",                              "pl": "Plan posiłków",                                   "zh-cn": "进食计划"},
    "Meal plan in connection with Chefkoch.de": {    "en": "Meal plan in connection with Chefkoch.de",        "de": "Speiseplan in Verbindung mit Chefkoch.de",        "ru": "План питания в связи с Chefkoch.de",              "pt": "Plano de refeições em conexão com Chefkoch.de",   "nl": "Maaltijdplan in verband met Chefkoch.de",         "fr": "Plan de repas en relation avec Chefkoch.de",      "it": "Piano dei pasti in connessione con Chefkoch.de",  "es": "Plan de comidas en relación con Chefkoch.de",     "pl": "Plan posiłków w połączeniu z Chefkoch.de",        "zh-cn": "與Chefkoch.de相關的用餐計劃"},
    "No idea": {                                     "en": "No idea",                                         "de": "Keine Ahnung",                                    "ru": "Без понятия",                                     "pt": "Nenhuma idéia",                                   "nl": "Geen idee",                                       "fr": "Aucune idée",                                     "it": "Nessuna idea",                                    "es": "Ni idea",                                         "pl": "Brak pomysłu",                                    "zh-cn": "不知道"},
    "Settings for adapter weekplan": {               "en": "Settings for adapter weekplan",                   "de": "Einstellungen für den Adapterwochenplan",         "ru": "Настройки для недельного плана адаптера",         "pt": "Configurações para plano de semana do adaptador", "nl": "Instellingen voor adapter weekplan",              "fr": "Paramètres du plan hebdomadaire de l'adaptateur", "it": "Impostazioni per l'adattatore weekplan",          "es": "Configuración del plan semanal del adaptador",    "pl": "Ustawienia tygodniowego planu adaptera",          "zh-cn": "适配器周计划的设置"},
    "Weekly schedule": {                             "en": "Weekly schedule",                                 "de": "Wochenplan",                                      "ru": "Еженедельное расписание",                         "pt": "Horário semanal",                                 "nl": "Wekelijkse planning",                             "fr": "Horaire hebdomadaire",                            "it": "Programma settimanale",                           "es": "Programación semanal",                            "pl": "Tygodniowy harmonogram",                          "zh-cn": "每周计划"},
    "weekplan adapter settings": {                   "en": "weekplan adapter settings",                       "de": "Wochenplan-Adaptereinstellungen",                 "ru": "настройки адаптера недельного плана",             "pt": "configurações do adaptador de plano semanal",     "nl": "weekplan adapter instellingen",                   "fr": "paramètres de l'adaptateur de plan hebdomadaire", "it": "Impostazioni dell'adattatore weekplan",           "es": "configuración del adaptador de plan de semana",   "pl": "ustawienia adaptera planu tygodnia",              "zh-cn": "周计划适配器设置"},
    "option1": {                                     "ru": "Опция 1",                                         "pt": "Opção 1",                                         "nl": "Optie 1",                                         "fr": "Option 1",                                        "it": "opzione 1",                                       "es": "Opción 1",                                        "pl": "opcja 1",                                         "zh-cn": "选项1"},
    "option2": {                                     "ru": "option2",                                         "pt": "opção 2",                                         "nl": "Optie 2",                                         "fr": "Option 2",                                        "it": "opzione 2",                                       "es": "opcion 2",                                        "pl": "Opcja 2",                                         "zh-cn": "选项2"},
};