/*global systemDictionary:true */
'use strict';

systemDictionary = {
    " are the ingredients for the recipe": {         "en": " are the ingredients for the recipe",             "de": "sind die Zutaten für das Rezept",                 "ru": "ингредиенты для рецепта",                         "pt": "são os ingredientes da receita",                  "nl": "zijn de ingrediënten voor het recept",            "fr": "sont les ingrédients de la recette",              "it": "sono gli ingredienti della ricetta",              "es": "son los ingredientes de la receta",               "pl": "są składnikami przepisu",                         "zh-cn": "是食谱的成分"},
    " is a unique number for the entry": {           "en": " is a unique number for the entry",               "de": "ist eine eindeutige Nummer für den Eintrag",      "ru": "уникальный номер для записи",                     "pt": "é um número único para a entrada",                "nl": "is een uniek nummer voor de vermelding",          "fr": "est un numéro unique pour l'entrée",              "it": "è un numero univoco per la voce",                 "es": "es un número único para la entrada",              "pl": "to niepowtarzalny numer wpisu",                   "zh-cn": "是条目的唯一编号"},
    " is the link to Chefkoch.de": {                 "en": " is the link to Chefkoch.de",                     "de": "ist der Link zu Chefkoch.de",                     "ru": "это ссылка на Chefkoch.de",                       "pt": "é o link para Chefkoch.de",                       "nl": "is de link naar Chefkoch.de",                     "fr": "est le lien vers Chefkoch.de",                    "it": "è il collegamento a Chefkoch.de",                 "es": "es el enlace a Chefkoch.de",                      "pl": "to link do Chefkoch.de",                          "zh-cn": "是到Chefkoch.de的链接"},
    " is the name of the court": {                   "en": " is the name of the court",                       "de": "ist der Name des Gerichts",                       "ru": "это название суда",                               "pt": "é o nome do tribunal",                            "nl": "is de naam van de rechtbank",                     "fr": "est le nom du tribunal",                          "it": "è il nome della corte",                           "es": "es el nombre de la corte",                        "pl": "to nazwa sądu",                                   "zh-cn": "是法院的名字"},
    " is the preparation of the recipe": {           "en": " is the preparation of the recipe",               "de": "ist die Vorbereitung des Rezepts",                "ru": "это подготовка рецепта",                          "pt": "é a preparação da receita",                       "nl": "is de voorbereiding van het recept",              "fr": "est la préparation de la recette",                "it": "è la preparazione della ricetta",                 "es": "es la preparación de la receta",                  "pl": "to przygotowanie przepisu",                       "zh-cn": "是食谱的准备"},
    "Datapoint from the Echo System": {              "en": "Datapoint from the Echo System",                  "de": "Datenpunkt aus dem Echo-System",                  "ru": "Datapoint из системы Echo",                       "pt": "Datapoint do Echo System",                        "nl": "Datapunt van het echosysteem",                    "fr": "Point de données du système Echo",                "it": "Datapoint da Echo System",                        "es": "Punto de datos del sistema Echo",                 "pl": "Punkt danych z systemu Echo",                     "zh-cn": "来自回声系统的数据点"},
    "Maintain Alexa shopping list": {                "en": "Maintain Alexa shopping list",                    "de": "Pflegen Sie die Alexa-Einkaufsliste",             "ru": "Ведение списка покупок Alexa",                    "pt": "Manter lista de compras Alexa",                   "nl": "Onderhoud Alexa-boodschappenlijst",               "fr": "Maintenir la liste de courses Alexa",             "it": "Mantieni la lista della spesa di Alexa",          "es": "Mantener la lista de compras de Alexa",           "pl": "Utrzymuj listę zakupów Alexa",                    "zh-cn": "维护Alexa购物清单"},
    "Meal plan": {                                   "en": "Meal plan",                                       "de": "Essensplan",                                      "ru": "План Питания",                                    "pt": "Plano de refeição",                               "nl": "Maaltijdplan",                                    "fr": "Plan de repas",                                   "it": "Piano pasto",                                     "es": "Régimen de comidas",                              "pl": "Plan posiłków",                                   "zh-cn": "进食计划"},
    "Meal plan in connection with Chefkoch.de": {    "en": "Meal plan in connection with Chefkoch.de",        "de": "Speiseplan in Verbindung mit Chefkoch.de",        "ru": "План питания в связи с Chefkoch.de",              "pt": "Plano de refeições em conexão com Chefkoch.de",   "nl": "Maaltijdplan in verband met Chefkoch.de",         "fr": "Plan de repas en relation avec Chefkoch.de",      "it": "Piano dei pasti in connessione con Chefkoch.de",  "es": "Plan de comidas en relación con Chefkoch.de",     "pl": "Plan posiłków w połączeniu z Chefkoch.de",        "zh-cn": "與Chefkoch.de相關的用餐計劃"},
    "No idea": {                                     "en": "No idea",                                         "de": "Keine Ahnung",                                    "ru": "Без понятия",                                     "pt": "Nenhuma idéia",                                   "nl": "Geen idee",                                       "fr": "Aucune idée",                                     "it": "Nessuna idea",                                    "es": "Ni idea",                                         "pl": "Brak pomysłu",                                    "zh-cn": "不知道"},
    "Settings for adapter weekplan": {               "en": "Settings for adapter weekplan",                   "de": "Einstellungen für den Adapterwochenplan",         "ru": "Настройки для недельного плана адаптера",         "pt": "Configurações para plano de semana do adaptador", "nl": "Instellingen voor adapter weekplan",              "fr": "Paramètres du plan hebdomadaire de l'adaptateur", "it": "Impostazioni per l'adattatore weekplan",          "es": "Configuración del plan semanal del adaptador",    "pl": "Ustawienia tygodniowego planu adaptera",          "zh-cn": "适配器周计划的设置"},
    "Weekly schedule": {                             "en": "Weekly schedule",                                 "de": "Wochenplan",                                      "ru": "Еженедельное расписание",                         "pt": "Horário semanal",                                 "nl": "Wekelijkse planning",                             "fr": "Horaire hebdomadaire",                            "it": "Programma settimanale",                           "es": "Programación semanal",                            "pl": "Tygodniowy harmonogram",                          "zh-cn": "每周计划"},
    "weekplan adapter settings": {                   "en": "weekplan adapter settings",                       "de": "Wochenplan-Adaptereinstellungen",                 "ru": "настройки адаптера недельного плана",             "pt": "configurações do adaptador de plano semanal",     "nl": "weekplan adapter instellingen",                   "fr": "paramètres de l'adaptateur de plan hebdomadaire", "it": "Impostazioni dell'adattatore weekplan",           "es": "configuración del adaptador de plan de semana",   "pl": "ustawienia adaptera planu tygodnia",              "zh-cn": "周计划适配器设置"},
    "with Alexa": {                                  "en": "with Alexa",                                      "de": "mit Alexa",                                       "ru": "с Алекса",                                        "pt": "com Alexa",                                       "nl": "met Alexa",                                       "fr": "avec Alexa",                                      "it": "con Alexa",                                       "es": "con Alexa",                                       "pl": "z Alexą",                                         "zh-cn": "与Alexa"},
    "with Alexa voice output": {                     "en": "with Alexa voice output",                         "de": "mit Alexa Sprachausgabe",                         "ru": "с голосовым выводом Alexa",                       "pt": "com saída de voz Alexa",                          "nl": "met Alexa-spraakuitvoer",                         "fr": "avec sortie vocale Alexa",                        "it": "con l'uscita vocale di Alexa",                    "es": "con salida de voz Alexa",                         "pl": "z wyjściem głosowym Alexa",                       "zh-cn": "带Alexa语音输出"},
};