/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "option1": {                                     "en": "option1",                                         "de": "Option 1",                                        "ru": "Опция 1",                                         "pt": "Opção 1",                                         "nl": "Optie 1",                                         "fr": "Option 1",                                        "it": "opzione 1",                                       "es": "Opción 1",                                        "pl": "opcja 1",                                         "zh-cn": "选项1"},
    "option2": {                                     "en": "option2",                                         "de": "Option 2",                                        "ru": "option2",                                         "pt": "opção 2",                                         "nl": "Optie 2",                                         "fr": "Option 2",                                        "it": "opzione 2",                                       "es": "opcion 2",                                        "pl": "Opcja 2",                                         "zh-cn": "选项2"},
    "Wochenplan": {                                  "en": "Weekplan",                                        "de": "Wochenplan",                                      "ru": "План на неделю",                                  "pt": "Plano de semana",                                 "nl": "Weekplan",                                        "fr": "Plan de la semaine",                              "it": "Weekplan",                                        "es": "Plan semanal",                                    "pl": "Plan tygodnia",                                   "zh-cn": "周计划"},
    "Essensplan": {                                  "en": "Meal plan",                                       "de": "Essensplan",                                      "ru": "План Питания",                                    "pt": "Plano de refeição",                               "nl": "Maaltijdplan",                                    "fr": "Plan de repas",                                   "it": "Piano pasto",                                     "es": "Régimen de comidas",                              "pl": "Plan posiłków",                                   "zh-cn": "进食计划"},
    "Einstellungen für Adapter Wochenplan": {        "en": "Adapter settings for weekplan",                   "de": "Adaptereinstellungen für Wochenplan",             "ru": "Настройки адаптера для недельного плана",         "pt": "Configurações do adaptador para plano de semana", "nl": "Adapterinstellingen voor weekplan",               "fr": "Paramètres de l'adaptateur pour le plan hebdomadaire", "it": "Impostazioni dell'adattatore per weekplan",       "es": "Configuración del adaptador para plan de semana", "pl": "Ustawienia adaptera dla planu tygodnia",          "zh-cn": "周计划的适配器设置"},
    "weekplan adapter settings": {                   "de": "Adaptereinstellungen für weekplan",               "ru": "Настройки адаптера для weekplan",                 "pt": "Configurações do adaptador para weekplan",        "nl": "Adapterinstellingen voor weekplan",               "fr": "Paramètres d'adaptateur pour weekplan",           "it": "Impostazioni dell'adattatore per weekplan",       "es": "Ajustes del adaptador para weekplan",             "pl": "Ustawienia adaptera dla weekplan",                "zh-cn": "weekplan的适配器设置"},
};